// Code generated by surface-gen; DO NOT EDIT.
// Operations the sdk surface exposes, as hey-api route filters,
// generated from backend/openapi/surfaces.yaml.
export const surfaceOps = [
  "POST /v1/email/messages",
  "POST /v1/email/batches",
  "GET /v1/email/messages/{message_id}",
  "GET /v1/email/messages",
  "POST /v1/email/templates",
  "GET /v1/email/templates",
  "GET /v1/email/templates/{template_id}",
  "PATCH /v1/email/templates/{template_id}",
  "DELETE /v1/email/templates/{template_id}",
  "POST /v1/email/templates/{template_id}/publish",
  "GET /v1/email/templates/{template_id}/versions",
  "GET /v1/email/templates/{template_id}/versions/{version_id}",
  "POST /v1/sms/messages",
  "POST /v1/sms/batches",
  "GET /v1/sms/messages/{message_id}",
  "GET /v1/sms/messages",
  "GET /v1/sms/templates",
  "GET /v1/sms/templates/{template_ref}",
];
