// Code generated by surface-gen; DO NOT EDIT.
// Operations the sdk surface exposes, as hey-api route filters,
// generated from backend/openapi/surfaces.yaml.
export const surfaceOps = [
  "POST /v1/email/messages",
  "GET /v1/email/messages/{message_id}",
  "GET /v1/email/messages",
];
