// Code generated by surface-gen; DO NOT EDIT.
import { createContact, deleteContact, getContact, listContacts } from "../generated/sdk.gen.js";
import type { Contact, CreateContactData, DeleteContactData, GetContactData, ListContactsData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { Contact };
export type ContactListQuery = NonNullable<ListContactsData["query"]>;
export type ContactCreateParams = NonNullable<CreateContactData["body"]>;

export class ContactsResourceBase extends Resource {
  /**
   * List the workspace's contacts as a cursor page, newest first. Look one up by exact email or external_id, or search by email substring.
   *
   * @example Iterate every contact, or take one page
   * for await (const contact of bird.contacts.list({ q: "acme.com" })) {
   *   console.log(contact.id, contact.email);
   * }
   * const page = await bird.contacts.list({ limit: 50 }); // page.data, page.next_cursor
   */
  list(query?: ContactListQuery, options?: RequestOptions): PaginatedPromise<Contact> {
    return this.paginated<Contact>("GET", options, ({ signal, headers }, cursor) =>
      listContacts({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Get a single contact by ID (`con_`-prefixed). Look up an ID by exact email or external_id with `contacts.list`.
   *
   * @example Fetch a contact by id
   * const contact = await bird.contacts.get("con_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(contact.email, contact.first_name);
   */
  get(contactId: string, options?: RequestOptions): APIPromise<Contact> {
    return this.call<Contact>("GET", options, ({ signal, headers }) =>
      getContact({ client: this.client, path: { contact_id: contactId }, headers, signal }));
  }

  /**
   * Create a contact by email address in the workspace. Fails with a conflict if the email or external_id is already used by another contact. For bulk import or create-or-update semantics use `contacts.batch`.
   *
   * @example Create a contact
   * const contact = await bird.contacts.create({
   *   email: "jane@acme.com",
   *   first_name: "Jane",
   * });
   * console.log(contact.id); // "con_…"
   */
  create(params: ContactCreateParams, options?: RequestOptions): APIPromise<Contact> {
    return this.call<Contact>("POST", options, ({ signal, headers }) =>
      createContact({ client: this.client, body: params, headers, signal }));
  }

  /**
   * Delete a contact and remove it from every audience it belongs to. Suppression records for the address are unaffected.
   *
   * @example Delete a contact by id
   * await bird.contacts.delete("con_01krdgeqcxet5s7t44vh8rt9mg");
   */
  delete(contactId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteContact({ client: this.client, path: { contact_id: contactId }, headers, signal }));
  }
}
