// Code generated by surface-gen; DO NOT EDIT.
import { archiveContactProperty, getContactProperty, listContactProperties, unarchiveContactProperty } from "../generated/sdk.gen.js";
import type { ArchiveContactPropertyData, ContactProperty, GetContactPropertyData, ListContactPropertiesData, UnarchiveContactPropertyData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { ContactProperty };
export type ContactPropertyListQuery = NonNullable<ListContactPropertiesData["query"]>;

export class ContactPropertiesResourceBase extends Resource {
  /**
   * List the workspace's contact properties as a cursor page, newest first. Archived properties are included, marked by their archived flag.
   *
   * @example Iterate every contact property, or take one page
   * for await (const prop of bird.contactProperties.list()) {
   *   console.log(prop.key, prop.type);
   * }
   * const page = await bird.contactProperties.list({ limit: 50 }); // page.data, page.next_cursor
   */
  list(query?: ContactPropertyListQuery, options?: RequestOptions): PaginatedPromise<ContactProperty> {
    return this.paginated<ContactProperty>("GET", options, ({ signal, headers }, cursor) =>
      listContactProperties({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Get a single contact property by ID: key, type, fallback value, and archived state.
   *
   * @example Fetch a contact property by id
   * const prop = await bird.contactProperties.get("cp_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(prop.key, prop.type);
   */
  get(propertyId: string, options?: RequestOptions): APIPromise<ContactProperty> {
    return this.call<ContactProperty>("GET", options, ({ signal, headers }) =>
      getContactProperty({ client: this.client, path: { property_id: propertyId }, headers, signal }));
  }

  /**
   * Archive a contact property: the key is rejected in new contact writes and stops rendering in templates, while stored values remain readable. The key stays reserved and counts toward the 200-property limit; reverse with `contact_properties.unarchive`.
   *
   * @example Archive a property, retiring the field without deleting its data
   * const prop = await bird.contactProperties.archive("cp_01krdgeqcxet5s7t44vh8rt9mg");
   * console.log(prop.key, prop.archived);
   */
  archive(propertyId: string, options?: RequestOptions): APIPromise<ContactProperty> {
    return this.call<ContactProperty>("POST", options, ({ signal, headers }) =>
      archiveContactProperty({ client: this.client, path: { property_id: propertyId }, headers, signal }));
  }

  /**
   * Reactivate an archived contact property so its key is accepted in contact writes and renders in templates again. Fails with a conflict if the property is not archived.
   *
   * @example Restore an archived property
   * await bird.contactProperties.unarchive("cp_01krdgeqcxet5s7t44vh8rt9mg");
   */
  unarchive(propertyId: string, options?: RequestOptions): APIPromise<ContactProperty> {
    return this.call<ContactProperty>("POST", options, ({ signal, headers }) =>
      unarchiveContactProperty({ client: this.client, path: { property_id: propertyId }, headers, signal }));
  }
}
