// Code generated by surface-gen; DO NOT EDIT.
import { getEmailStatsByBounceCode, getEmailStatsByBroadcast, getEmailStatsByCategory, getEmailStatsByClient, getEmailStatsByComplaintType, getEmailStatsByLocation, getEmailStatsByMailboxProvider, getEmailStatsByMailboxProviderRegion, getEmailStatsByRecipientDomain, getEmailStatsBySendingDomain, getEmailStatsBySendingIp, getEmailStatsByTag, getEmailStatsByTemplate, getEmailStatsDaily, getEmailStatsHourly, getEmailStatsSummary } from "../generated/sdk.gen.js";
import type { EmailStatsByBounceCodeResponse, EmailStatsByBroadcastResponse, EmailStatsByCategoryResponse, EmailStatsByClientResponse, EmailStatsByComplaintTypeResponse, EmailStatsByLocationResponse, EmailStatsByMailboxProviderRegionResponse, EmailStatsByMailboxProviderResponse, EmailStatsByRecipientDomainResponse, EmailStatsBySendingDomainResponse, EmailStatsBySendingIpResponse, EmailStatsByTemplateResponse, EmailStatsResponse, EmailStatsSummary, EmailStatsTagsResponse, GetEmailStatsByBounceCodeData, GetEmailStatsByBroadcastData, GetEmailStatsByCategoryData, GetEmailStatsByClientData, GetEmailStatsByComplaintTypeData, GetEmailStatsByLocationData, GetEmailStatsByMailboxProviderData, GetEmailStatsByMailboxProviderRegionData, GetEmailStatsByRecipientDomainData, GetEmailStatsBySendingDomainData, GetEmailStatsBySendingIpData, GetEmailStatsByTagData, GetEmailStatsByTemplateData, GetEmailStatsDailyData, GetEmailStatsHourlyData, GetEmailStatsSummaryData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { EmailStatsSummary };
export type { EmailStatsResponse };
export type { EmailStatsTagsResponse };
export type { EmailStatsByCategoryResponse };
export type { EmailStatsBySendingIpResponse };
export type { EmailStatsBySendingDomainResponse };
export type { EmailStatsByRecipientDomainResponse };
export type { EmailStatsByMailboxProviderResponse };
export type { EmailStatsByMailboxProviderRegionResponse };
export type { EmailStatsByTemplateResponse };
export type { EmailStatsByLocationResponse };
export type { EmailStatsByClientResponse };
export type { EmailStatsByBounceCodeResponse };
export type { EmailStatsByComplaintTypeResponse };
export type { EmailStatsByBroadcastResponse };
export type EmailStatsSummaryQuery = NonNullable<GetEmailStatsSummaryData["query"]>;
export type EmailStatsDailyQuery = NonNullable<GetEmailStatsDailyData["query"]>;
export type EmailStatsHourlyQuery = NonNullable<GetEmailStatsHourlyData["query"]>;
export type EmailStatsByTagQuery = NonNullable<GetEmailStatsByTagData["query"]>;
export type EmailStatsByCategoryQuery = NonNullable<GetEmailStatsByCategoryData["query"]>;
export type EmailStatsBySendingIpQuery = NonNullable<GetEmailStatsBySendingIpData["query"]>;
export type EmailStatsBySendingDomainQuery = NonNullable<GetEmailStatsBySendingDomainData["query"]>;
export type EmailStatsByRecipientDomainQuery = NonNullable<GetEmailStatsByRecipientDomainData["query"]>;
export type EmailStatsByMailboxProviderQuery = NonNullable<GetEmailStatsByMailboxProviderData["query"]>;
export type EmailStatsByMailboxProviderRegionQuery = NonNullable<GetEmailStatsByMailboxProviderRegionData["query"]>;
export type EmailStatsByTemplateQuery = NonNullable<GetEmailStatsByTemplateData["query"]>;
export type EmailStatsByLocationQuery = NonNullable<GetEmailStatsByLocationData["query"]>;
export type EmailStatsByClientQuery = NonNullable<GetEmailStatsByClientData["query"]>;
export type EmailStatsByBounceCodeQuery = NonNullable<GetEmailStatsByBounceCodeData["query"]>;
export type EmailStatsByComplaintTypeQuery = NonNullable<GetEmailStatsByComplaintTypeData["query"]>;
export type EmailStatsByBroadcastQuery = NonNullable<GetEmailStatsByBroadcastData["query"]>;

export class EmailStatsResource extends Resource {
  /**
   * Aggregate email KPIs for one period: sends, delivered, bounces, complaints, opens, clicks, their rates, and latency percentiles. `from`/`to` are both YYYY-MM-DD days or both RFC 3339 instants (hour grain); add `compare=previous_period` for deltas versus the prior window. For a per-day or per-hour series use email_stats_daily or email_stats_hourly.
   *
   * @example Summary for a month
   * const s = await bird.email.stats.summary({ from: "2026-05-01", to: "2026-05-31" });
   * console.log(s.sends_accepted, s.delivery.delivered);
   */
  summary(query?: EmailStatsSummaryQuery, options?: RequestOptions): APIPromise<EmailStatsSummary> {
    return this.call<EmailStatsSummary>("GET", options, ({ signal, headers }) =>
      getEmailStatsSummary({ client: this.client, query, headers, signal }));
  }

  /**
   * Per-day email stats series (counts, rates, latency percentiles), gap-filled with zero rows, max 365 days. At most one filter of `category`, `sending_domain`, `tag`, `sending_ip`, `recipient_domain`, `template`. For hour resolution use email_stats_hourly; for one aggregate row use email_stats_summary.
   *
   * @example 
   * const series = await bird.email.stats.daily({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of series.data) console.log(row.bucket, row.delivery.delivered);
   */
  daily(query?: EmailStatsDailyQuery, options?: RequestOptions): APIPromise<EmailStatsResponse> {
    return this.call<EmailStatsResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsDaily({ client: this.client, query, headers, signal }));
  }

  /**
   * Per-hour email stats series, gap-filled with zero rows, max 720 hours (30 days). Takes the same single-dimension filters as email_stats_daily; for longer ranges use email_stats_daily, for one aggregate row use email_stats_summary.
   *
   * @example 
   * const series = await bird.email.stats.hourly({ from: "2026-05-01", to: "2026-05-02" });
   * for (const row of series.data) console.log(row.bucket, row.delivery.delivered);
   */
  hourly(query?: EmailStatsHourlyQuery, options?: RequestOptions): APIPromise<EmailStatsResponse> {
    return this.call<EmailStatsResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsHourly({ client: this.client, query, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by tag, one row per `name:value` pair set at send time; ranked by `sort` (default `processed`). `include_trend=true` adds a per-bucket rate series to each row.
   *
   * @example Top 10 tags by delivered
   * const { data } = await bird.email.stats.byTag({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "delivered",
   *   limit: 10,
   * });
   * for (const row of data) console.log(row.tag, row.delivery.delivered);
   */
  byTag(query?: EmailStatsByTagQuery, options?: RequestOptions): APIPromise<EmailStatsTagsResponse> {
    return this.call<EmailStatsTagsResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsByTag({ client: this.client, query, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by category (`transactional` versus `marketing`), ranked by `sort` (default `processed`). `include_trend=true` adds a per-bucket rate series to each row.
   *
   * @example 
   * const { data } = await bird.email.stats.byCategory({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of data) console.log(row.category, row.delivery.delivered);
   */
  byCategory(query?: EmailStatsByCategoryQuery, options?: RequestOptions): APIPromise<EmailStatsByCategoryResponse> {
    return this.call<EmailStatsByCategoryResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsByCategory({ client: this.client, query, headers, signal }));
  }

  /**
   * Delivery and bounce stats grouped by sending IP; `sort=bounces.block` surfaces reputation-damaged IPs first. No engagement, complaint, or accepted/processed counts per IP; use email_stats_daily for workspace-wide figures.
   *
   * @example 
   * const { data } = await bird.email.stats.bySendingIp({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "bounces.block",
   *   limit: 20,
   * });
   * for (const row of data) console.log(row.sending_ip, row.delivery.delivered);
   */
  bySendingIp(query?: EmailStatsBySendingIpQuery, options?: RequestOptions): APIPromise<EmailStatsBySendingIpResponse> {
    return this.call<EmailStatsBySendingIpResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsBySendingIp({ client: this.client, query, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by sending (`From`) domain; compare deliverability across the workspace's verified domains. For per-IP reputation use email_stats_by_sending_ip.
   *
   * @example 
   * const { data } = await bird.email.stats.bySendingDomain({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "delivery_rate",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.sending_domain, row.delivery.delivery_rate);
   */
  bySendingDomain(query?: EmailStatsBySendingDomainQuery, options?: RequestOptions): APIPromise<EmailStatsBySendingDomainResponse> {
    return this.call<EmailStatsBySendingDomainResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsBySendingDomain({ client: this.client, query, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by exact recipient mailbox domain (for example `gmail.com`). Finer-grained than email_stats_by_mailbox_provider, which buckets domains into providers.
   *
   * @example 
   * const { data } = await bird.email.stats.byRecipientDomain({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "bounce_rate",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.recipient_domain, row.delivery.bounce_rate);
   */
  byRecipientDomain(query?: EmailStatsByRecipientDomainQuery, options?: RequestOptions): APIPromise<EmailStatsByRecipientDomainResponse> {
    return this.call<EmailStatsByRecipientDomainResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsByRecipientDomain({ client: this.client, query, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by recipient mailbox provider (`gmail`, `microsoft`, `yahoo`, ...); covers the delivery stage onward, no accepted/processed counts. For a per-region split use email_stats_by_mailbox_provider_region; for exact destination domains use email_stats_by_recipient_domain.
   *
   * @example 
   * const { data } = await bird.email.stats.byMailboxProvider({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.mailbox_provider, row.delivery.delivered);
   */
  byMailboxProvider(query?: EmailStatsByMailboxProviderQuery, options?: RequestOptions): APIPromise<EmailStatsByMailboxProviderResponse> {
    return this.call<EmailStatsByMailboxProviderResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsByMailboxProvider({ client: this.client, query, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by mailbox provider and provider region pair (for example `gmail` in `NA`); covers the delivery stage onward, no accepted/processed counts. For the provider-level view use email_stats_by_mailbox_provider.
   *
   * @example 
   * const { data } = await bird.email.stats.byMailboxProviderRegion({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.mailbox_provider, row.mailbox_provider_region, row.delivery.delivered);
   */
  byMailboxProviderRegion(query?: EmailStatsByMailboxProviderRegionQuery, options?: RequestOptions): APIPromise<EmailStatsByMailboxProviderRegionResponse> {
    return this.call<EmailStatsByMailboxProviderRegionResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsByMailboxProviderRegion({ client: this.client, query, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by the template used at send time, keyed by template id (`emt_…`); only templated sends appear. To track a single template over time, pass `template` to email_stats_daily instead.
   *
   * @example 
   * const { data } = await bird.email.stats.byTemplate({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "open_rate",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.template_id, row.engagement.open_rate);
   */
  byTemplate(query?: EmailStatsByTemplateQuery, options?: RequestOptions): APIPromise<EmailStatsByTemplateResponse> {
    return this.call<EmailStatsByTemplateResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsByTemplate({ client: this.client, query, headers, signal }));
  }

  /**
   * Opens and clicks grouped by country, region, or city (`group_by`); engagement counts only, no delivery counts or rates. For engagement by mail client or device use email_stats_by_client.
   *
   * @example 
   * const { data } = await bird.email.stats.byLocation({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.country, row.engagement.unique_opens);
   */
  byLocation(query?: EmailStatsByLocationQuery, options?: RequestOptions): APIPromise<EmailStatsByLocationResponse> {
    return this.call<EmailStatsByLocationResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsByLocation({ client: this.client, query, headers, signal }));
  }

  /**
   * Opens and clicks grouped by mail client, OS, or device type (`group_by`); engagement counts only, no delivery counts or rates. For engagement by geography use email_stats_by_location.
   *
   * @example 
   * const { data } = await bird.email.stats.byClient({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.email_client, row.engagement.unique_opens);
   */
  byClient(query?: EmailStatsByClientQuery, options?: RequestOptions): APIPromise<EmailStatsByClientResponse> {
    return this.call<EmailStatsByClientResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsByClient({ client: this.client, query, headers, signal }));
  }

  /**
   * Bounce counts grouped by the SMTP error code the receiving server returned, with the hard/soft/admin/block/undetermined split; failure side only. Use it to find what is driving bounces; for bounces by destination use email_stats_by_recipient_domain or email_stats_by_mailbox_provider.
   *
   * @example 
   * const { data } = await bird.email.stats.byBounceCode({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "bounced",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.smtp_error_code, row.bounced);
   */
  byBounceCode(query?: EmailStatsByBounceCodeQuery, options?: RequestOptions): APIPromise<EmailStatsByBounceCodeResponse> {
    return this.call<EmailStatsByBounceCodeResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsByBounceCode({ client: this.client, query, headers, signal }));
  }

  /**
   * Spam-complaint counts grouped by the feedback-loop complaint type (for example `abuse`, `fraud`, `virus`); complaint side only. For complaints by destination use email_stats_by_mailbox_provider or email_stats_by_recipient_domain.
   *
   * @example 
   * const { data } = await bird.email.stats.byComplaintType({ from: "2026-05-01", to: "2026-05-31" });
   * for (const row of data) console.log(row.feedback_type, row.complained);
   */
  byComplaintType(query?: EmailStatsByComplaintTypeQuery, options?: RequestOptions): APIPromise<EmailStatsByComplaintTypeResponse> {
    return this.call<EmailStatsByComplaintTypeResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsByComplaintType({ client: this.client, query, headers, signal }));
  }

  /**
   * Email delivery and engagement stats grouped by broadcast; only broadcast sends appear. Reflects roughly the last 30 days of activity; `include_trend` is not available here and returns 422.
   *
   * @example 
   * const { data } = await bird.email.stats.byBroadcast({
   *   from: "2026-05-01",
   *   to: "2026-05-31",
   *   sort: "click_rate",
   *   limit: 25,
   * });
   * for (const row of data) console.log(row.broadcast_id, row.engagement.click_rate);
   */
  byBroadcast(query?: EmailStatsByBroadcastQuery, options?: RequestOptions): APIPromise<EmailStatsByBroadcastResponse> {
    return this.call<EmailStatsByBroadcastResponse>("GET", options, ({ signal, headers }) =>
      getEmailStatsByBroadcast({ client: this.client, query, headers, signal }));
  }
}
