// Code generated by surface-gen; DO NOT EDIT.
import { deleteEmailThread, getEmailThread, listEmailThreads, updateEmailThread } from "../generated/sdk.gen.js";
import type { DeleteEmailThreadData, EmailThread, GetEmailThreadData, ListEmailThreadsData, UpdateEmailThreadData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { EmailThread };
export type MailboxThreadListQuery = NonNullable<ListEmailThreadsData["query"]>;
export type MailboxThreadUpdateParams = NonNullable<UpdateEmailThreadData["body"]>;
export type MailboxThreadDeleteQuery = NonNullable<DeleteEmailThreadData["query"]>;

export class MailboxThreadResource extends Resource {
  /**
   * List mailbox conversations as a cursor page, most recently active first. `label` selects the view — inbox (default), archive, spam, blocked, or a custom label. Filter by mailbox, contact, participant address, or subject substring.
   *
   * @example List conversation threads
   * for await (const thread of bird.mailboxThread.list({ mailbox_id: "mbx_01abc" })) {
   *   console.log(thread.id, thread.subject);
   * }
   */
  list(query?: MailboxThreadListQuery, options?: RequestOptions): PaginatedPromise<EmailThread> {
    return this.paginated<EmailThread>("GET", options, ({ signal, headers }, cursor) =>
      listEmailThreads({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }

  /**
   * Get one conversation: participants, counts, labels, read state. Fetch its messages with the thread messages endpoint.
   *
   * @example Get a thread
   * const thread = await bird.mailboxThread.get("thr_01abc");
   * console.log(thread.subject);
   */
  get(threadId: string, options?: RequestOptions): APIPromise<EmailThread> {
    return this.call<EmailThread>("GET", options, ({ signal, headers }) =>
      getEmailThread({ client: this.client, path: { thread_id: threadId }, headers, signal }));
  }

  /**
   * Add or remove labels on a conversation — adding `spam` files it as spam, adding `archive` clears it out of the inbox, adding `inbox` brings it back — or link/unlink a contact.
   *
   * @example Apply label changes to a thread
   * const thread = await bird.mailboxThread.update("thr_01abc", {
   *   labels: { add: ["archive"] },
   * });
   * console.log(thread.id);
   */
  update(threadId: string, params: MailboxThreadUpdateParams = {}, options?: RequestOptions): APIPromise<EmailThread> {
    return this.call<EmailThread>("PATCH", options, ({ signal, headers }) =>
      updateEmailThread({ client: this.client, path: { thread_id: threadId }, body: params, headers, signal }));
  }

  /**
   * Move a conversation and all its messages to trash (purged after 30 days), or delete permanently with ?permanent=true.
   *
   * @example Delete a thread
   * await bird.mailboxThread.delete("thr_01abc", { permanent: true });
   */
  delete(threadId: string, query?: MailboxThreadDeleteQuery, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("DELETE", options, ({ signal, headers }) =>
      deleteEmailThread({ client: this.client, path: { thread_id: threadId }, query, headers, signal }));
  }
}
