// Code generated by surface-gen; DO NOT EDIT.
import { getRealtimeAppChannel, listRealtimeAppChannelMembers, listRealtimeAppChannels } from "../generated/sdk.gen.js";
import type { GetRealtimeAppChannelData, ListRealtimeAppChannelMembersData, ListRealtimeAppChannelsData, RealtimeChannelInfo, RealtimeChannelMembers, RealtimeChannelsList } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { RealtimeChannelsList };
export type { RealtimeChannelInfo };
export type { RealtimeChannelMembers };
export type RealtimeChannelListQuery = NonNullable<ListRealtimeAppChannelsData["query"]>;
export type RealtimeChannelGetQuery = NonNullable<GetRealtimeAppChannelData["query"]>;

export class RealtimeChannelsResource extends Resource {
  /**
   * @example List the occupied presence channels with their member counts
   * const { data } = await bird.realtime.channels.list("rap_01krdgeqcxet5s7t44vh8rt9mg", {
   *   prefix: "presence-",
   *   include: ["member_count"],
   * });
   * for (const channel of data) console.log(channel.name, channel.member_count);
   */
  list(realtimeAppId: string, query?: RealtimeChannelListQuery, options?: RequestOptions): APIPromise<RealtimeChannelsList> {
    return this.call<RealtimeChannelsList>("GET", options, ({ signal, headers }) =>
      listRealtimeAppChannels({ client: this.client, path: { realtime_app_id: realtimeAppId }, query, headers, signal }), ["RealtimeKey", "RealtimeSecret"]);
  }

  /**
   * @example Check whether anyone is in a channel
   * const channel = await bird.realtime.channels.get("rap_01krdgeqcxet5s7t44vh8rt9mg", "presence-lobby", {
   *   include: ["member_count"],
   * });
   * console.log(channel.occupied, channel.member_count);
   */
  get(realtimeAppId: string, channelName: string, query?: RealtimeChannelGetQuery, options?: RequestOptions): APIPromise<RealtimeChannelInfo> {
    return this.call<RealtimeChannelInfo>("GET", options, ({ signal, headers }) =>
      getRealtimeAppChannel({ client: this.client, path: { realtime_app_id: realtimeAppId, channel_name: channelName }, query, headers, signal }), ["RealtimeKey", "RealtimeSecret"]);
  }

  /**
   * @example Who is in the lobby
   * const { members } = await bird.realtime.channels.members("rap_01krdgeqcxet5s7t44vh8rt9mg", "presence-lobby");
   * for (const member of members) console.log(member.member_id);
   */
  members(realtimeAppId: string, channelName: string, options?: RequestOptions): APIPromise<RealtimeChannelMembers> {
    return this.call<RealtimeChannelMembers>("GET", options, ({ signal, headers }) =>
      listRealtimeAppChannelMembers({ client: this.client, path: { realtime_app_id: realtimeAppId, channel_name: channelName }, headers, signal }), ["RealtimeKey", "RealtimeSecret"]);
  }
}
