// Code generated by surface-gen; DO NOT EDIT.
import { disconnectRealtimeAppMember, sendRealtimeAppMemberEvent } from "../generated/sdk.gen.js";
import type { DisconnectRealtimeAppMemberData, SendRealtimeAppMemberEventData } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type RealtimeMemberSendParams = NonNullable<SendRealtimeAppMemberEventData["body"]>;

export class RealtimeMembersResource extends Resource {
  /**
   * @example Notify one person wherever they are signed in
   * await bird.realtime.members.send("rap_01krdgeqcxet5s7t44vh8rt9mg", "user_42", {
   *   event: "order-shipped",
   *   data: { order_id: "ord_123" },
   * });
   */
  send(realtimeAppId: string, memberId: string, params: RealtimeMemberSendParams, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("POST", options, ({ signal, headers }) =>
      sendRealtimeAppMemberEvent({ client: this.client, path: { realtime_app_id: realtimeAppId, member_id: memberId }, body: params, headers, signal }), ["RealtimeKey", "RealtimeSecret"]);
  }

  /**
   * @example Kick a member off every connection
   * await bird.realtime.members.disconnect("rap_01krdgeqcxet5s7t44vh8rt9mg", "user_42");
   */
  disconnect(realtimeAppId: string, memberId: string, options?: RequestOptions): APIPromise<void> {
    return this.call<void>("POST", options, ({ signal, headers }) =>
      disconnectRealtimeAppMember({ client: this.client, path: { realtime_app_id: realtimeAppId, member_id: memberId }, headers, signal }), ["RealtimeKey", "RealtimeSecret"]);
  }
}
