// Code generated by surface-gen; DO NOT EDIT.
import { publishRealtimeAppBatch, publishRealtimeAppEvent } from "../generated/sdk.gen.js";
import type { PublishRealtimeAppBatchData, PublishRealtimeAppEventData, RealtimeBatchPublishResult, RealtimePublishResult } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, RequestOptions } from "../core/result.js";

export type { RealtimePublishResult };
export type { RealtimeBatchPublishResult };
export type RealtimePublishParams = NonNullable<PublishRealtimeAppEventData["body"]>;
export type RealtimePublishBatchParams = NonNullable<PublishRealtimeAppBatchData["body"]>;

export class RealtimeResourceBase extends Resource {
  /**
   * @example Broadcast an event to a channel
   * const result = await bird.realtime.publish("rap_01krdgeqcxet5s7t44vh8rt9mg", {
   *   event: "order.updated",
   *   channels: ["orders", "presence-lobby"],
   *   data: { order_id: "ord_123", status: "shipped" },
   * });
   * console.log(result.data?.length); // one entry per channel
   */
  publish(realtimeAppId: string, params: RealtimePublishParams, options?: RequestOptions): APIPromise<RealtimePublishResult> {
    return this.call<RealtimePublishResult>("POST", options, ({ signal, headers }) =>
      publishRealtimeAppEvent({ client: this.client, path: { realtime_app_id: realtimeAppId }, body: params, headers, signal }), ["RealtimeKey", "RealtimeSecret"]);
  }

  /**
   * @example Publish two events in one call
   * await bird.realtime.publishBatch("rap_01krdgeqcxet5s7t44vh8rt9mg", {
   *   events: [
   *     { event: "order.created", channel: "orders", data: { id: 1 } },
   *     { event: "order.updated", channel: "orders", data: { id: 2 } },
   *   ],
   * });
   */
  publishBatch(realtimeAppId: string, params: RealtimePublishBatchParams, options?: RequestOptions): APIPromise<RealtimeBatchPublishResult> {
    return this.call<RealtimeBatchPublishResult>("POST", options, ({ signal, headers }) =>
      publishRealtimeAppBatch({ client: this.client, path: { realtime_app_id: realtimeAppId }, body: params, headers, signal }), ["RealtimeKey", "RealtimeSecret"]);
  }
}
