// Code generated by surface-gen; DO NOT EDIT.
import { getSmsMessage, listSmsMessages } from "../generated/sdk.gen.js";
import type { GetSmsMessageData, ListSmsMessagesData, SmsMessage } from "../generated/types.gen.js";
import { Resource } from "./base.js";
import type { APIPromise, PaginatedPromise, RequestOptions } from "../core/result.js";

export type { SmsMessage };
export type SmsListQuery = NonNullable<ListSmsMessagesData["query"]>;

export class SmsResourceBase extends Resource {
  /**
   * Get one SMS message by id: its current delivery status, segment breakdown, cost, and failure detail if it failed.
   *
   * @example Read a message back
   * const msg = await bird.sms.get("sms_abc123");
   * msg.status; // "accepted" | "delivered" | …
   */
  get(messageId: string, options?: RequestOptions): APIPromise<SmsMessage> {
    return this.call<SmsMessage>("GET", options, ({ signal, headers }) =>
      getSmsMessage({ client: this.client, path: { message_id: messageId }, headers, signal }));
  }

  /**
   * List SMS messages, newest first, as a cursor page ({data, next_cursor, …}). Pass next_cursor back as starting_after to fetch the next page. Filter by direction, status, category, recipient, sender, or tag.
   *
   * @example Iterate outbound messages
   * for await (const msg of bird.sms.list({ direction: "outbound" })) {
   *   console.log(msg.id, msg.status);
   * }
   */
  list(query?: SmsListQuery, options?: RequestOptions): PaginatedPromise<SmsMessage> {
    return this.paginated<SmsMessage>("GET", options, ({ signal, headers }, cursor) =>
      listSmsMessages({ client: this.client, query: { ...query, starting_after: cursor ?? query?.starting_after }, headers, signal }));
  }
}
