// Generated by docsnippet-gen — do not edit. Type-checks every TS
// @example snippet so it cannot drift from the SDK's real types.
import { BirdClient } from "@messagebird/sdk";
import { BirdRateLimitError, BirdValidationError, BirdAPIError } from "@messagebird/sdk";

declare const bird: BirdClient;
declare const rawBody: string;
declare const headers: Record<string, string>;

export async function _ex_0() {
await bird.audiences.addContacts("aud_01krdgeqcxet5s7t44vh8rt9mg", {
  contact_ids: ["con_1", "con_2"],
});
}

export async function _ex_1() {
const audience = await bird.audiences.create({ name: "Newsletter subscribers" });
console.log(audience.id); // "aud_…"
}

export async function _ex_2() {
await bird.audiences.delete("aud_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_3() {
const audience = await bird.audiences.get("aud_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_4() {
for await (const audience of bird.audiences.list()) {
  console.log(audience.id, audience.name);
}
}

export async function _ex_5() {
for await (const member of bird.audiences.listContacts("aud_01krdgeqcxet5s7t44vh8rt9mg")) {
  console.log(member.contact.id, member.joined_at);
}
}

export async function _ex_6() {
await bird.audiences.removeContact("aud_01krdgeqcxet5s7t44vh8rt9mg", "con_1");
}

export async function _ex_7() {
await bird.audiences.removeContacts("aud_01krdgeqcxet5s7t44vh8rt9mg", {
  contact_ids: ["con_1", "con_2"],
});
}

export async function _ex_8() {
await bird.audiences.update("aud_01krdgeqcxet5s7t44vh8rt9mg", { name: "Renamed" });
}

export async function _ex_9() {
const bird = new BirdClient({
  apiKey: process.env.BIRD_API_KEY!,
  region: "eu1", // optional — override the region from the key prefix
  baseUrl: "http://localhost:8080", // optional — overrides region entirely (local/self-hosted)
  timeout: 60_000, // per-attempt timeout in ms (default 60_000)
  maxRetries: 2, // retry budget for transient failures (default 2)
});
}

export async function _ex_10() {
await bird.contactProperties.archive("cp_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_11() {
const prop = await bird.contactProperties.create({ key: "plan", type: "string" });
console.log(prop.id); // "cp_…"
}

export async function _ex_12() {
const prop = await bird.contactProperties.get("cp_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_13() {
for await (const prop of bird.contactProperties.list()) {
  console.log(prop.key, prop.type);
}
}

export async function _ex_14() {
await bird.contactProperties.unarchive("cp_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_15() {
await bird.contactProperties.update("cp_01krdgeqcxet5s7t44vh8rt9mg", { fallback_value: "free" });
}

export async function _ex_16() {
const result = await bird.contacts.batch({
  contacts: [{ email: "jane@acme.com", first_name: "Jane" }],
});
}

export async function _ex_17() {
const contact = await bird.contacts.create({
  email: "jane@acme.com",
  first_name: "Jane",
});
console.log(contact.id); // "con_…"
}

export async function _ex_18() {
await bird.contacts.delete("con_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_19() {
const contact = await bird.contacts.get("con_01krdgeqcxet5s7t44vh8rt9mg");
contact.email;
}

export async function _ex_20() {
for await (const contact of bird.contacts.list({ search: "acme.com" })) {
  console.log(contact.id, contact.email);
}
const page = await bird.contacts.list({ limit: 50 }); // page.data, page.next_cursor
}

export async function _ex_21() {
const contact = await bird.contacts.update("con_01krdgeqcxet5s7t44vh8rt9mg", {
  first_name: "Jane",
});
}

export async function _ex_22() {
const domain = await bird.domains.create({ domain: "mail.acme.com" });
console.log(domain.id, domain.status); // "dom_…", "pending"
}

export async function _ex_23() {
await bird.domains.delete("dom_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_24() {
const domain = await bird.domains.get("dom_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_25() {
for await (const domain of bird.domains.list()) {
  console.log(domain.id, domain.status);
}
}

export async function _ex_26() {
await bird.domains.update("dom_01krdgeqcxet5s7t44vh8rt9mg", {
  settings: { click_tracking: true, open_tracking: true },
  tracking: { name: "links" },
});
}

export async function _ex_27() {
const domain = await bird.domains.verify("dom_01krdgeqcxet5s7t44vh8rt9mg");
console.log(domain.status); // "verified" once DNS is in place
}

export async function _ex_28() {
await bird.email.cancel("em_abc123");
}

export async function _ex_29() {

try {
  await bird.email.send({
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["delivered@messagebird.dev"],
    subject: "Hello from Bird",
    html: "<p>My first Bird email.</p>",
  });
} catch (err) {
  if (err instanceof BirdRateLimitError) console.log(`rate limited — retry in ${err.retryAfter}s`);
  else if (err instanceof BirdValidationError) console.error(err.details);
  else if (err instanceof BirdAPIError) console.error(err.code, err.requestId);
  else throw err;
}
}

export async function _ex_30() {
const msg = await bird.email.get("em_abc123");
msg.status; // "accepted" | "processed" | "delivered" | "bounced" | …
msg.delivered_count;
msg.bounced_count;
}

export async function _ex_31() {
for await (const message of bird.email.list({ status: "bounced" })) {
  console.log(message.id);
}
}

export async function _ex_32() {
for await (const message of bird.email.list({ status: "bounced" })) {
  console.log(message.id);
}
const page = await bird.email.list({ limit: 50 }); // page.data, page.next_cursor
}

export async function _ex_33() {
const { data, error } = await bird.email
  .send({
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["delivered@messagebird.dev"],
    subject: "Hello from Bird",
    html: "<p>My first Bird email.</p>",
  })
  .safe();
if (error) console.error(error.message);
else console.log(data.id);
}

export async function _ex_34() {
const msg = await bird.email.send({
  from: { email: "onboarding@messagebird.dev", name: "Bird" },
  to: ["delivered@messagebird.dev"],
  subject: "Hello from Bird",
  html: "<p>My first Bird email.</p>",
});
console.log(msg.id, msg.status); // "em_…", "accepted"
}

export async function _ex_35() {
const batch = await bird.email.sendBatch([
  {
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["alice@example.com"],
    subject: "Your receipt",
    html: "<p>Thanks, Alice.</p>",
  },
  {
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["bob@example.com"],
    subject: "Your receipt",
    html: "<p>Thanks, Bob.</p>",
  },
]);
for (const item of batch.data) console.log(item.id, item.status);
}

export async function _ex_36() {
const msg = await bird.sms.get("sms_abc123");
msg.status; // "accepted" | "delivered" | …
}

export async function _ex_37() {
for await (const msg of bird.sms.list({ direction: "outbound" })) {
  console.log(msg.id, msg.status);
}
}

export async function _ex_38() {
const msg = await bird.sms.send({
  to: "+15551234567",
  text: "Your verification code is 123456.",
  category: "authentication",
});
console.log(msg.id, msg.status);
}

export async function _ex_39() {
const result = await bird.sms.sendBatch([
  { to: "+15551111111", text: "Hi Alice!", category: "marketing" },
  { to: "+15552222222", text: "Hi Bob!", category: "marketing" },
]);
}

export async function _ex_40() {
await bird.sms.send({
  to: "+15551234567",
  template: { name: "bird_otp_verification", parameters: { code: "123456" } },
});
}

export async function _ex_41() {
const tpl = await bird.smsTemplates.get("bird_otp_verification");
console.log(tpl.body, tpl.variables);
}

export async function _ex_42() {
const { data } = await bird.smsTemplates.list({ scope: "system" });
for (const tpl of data) console.log(tpl.id, tpl.name);
}

export async function _ex_43() {
const result = await bird.verify.verifications.check({
  to: { phone_number: "+15551234567" },
  code: "123456",
});
console.log(result.success);
}

export async function _ex_44() {
const verification = await bird.verify.verifications.create({
  to: { phone_number: "+15551234567" },
});
console.log(verification.id, verification.status);
}

export async function _ex_45() {
// Pass the RAW request body; set the secret via new BirdClient({ webhooks: { secret } }).
const event = bird.webhooks.unwrap(rawBody, headers);
console.log(event.type); // discriminated union — narrow on event.type
}

export async function _ex_46() {
const msg = await bird.whatsapp.get("wa_abc123");
msg.status; // "accepted" | "delivered" | …
}

export async function _ex_47() {
for await (const msg of bird.whatsapp.list({ status: ["delivered"] })) {
  console.log(msg.id, msg.status);
}
}

export async function _ex_48() {
const { data } = await bird.whatsapp.listEvents("wa_abc123");
for (const event of data) console.log(event.type, event.occurred_at);
}

export async function _ex_49() {
const msg = await bird.whatsapp.send({
  to: "+15551234567",
  template: {
    name: "bird_otp",
    components: [
      { type: "body", parameters: [{ type: "text", text: "123456" }] },
    ],
  },
});
console.log(msg.id, msg.status);
}

export async function _ex_50() {
const { data } = await bird.whatsappTemplates.list();
for (const tpl of data) console.log(tpl.name, tpl.status);
}
