// Generated by docsnippet-gen — do not edit. Type-checks every TS
// @example snippet so it cannot drift from the SDK's real types.
import { BirdClient } from "@messagebird/sdk";
import { BirdRateLimitError, BirdValidationError, BirdAPIError } from "@messagebird/sdk";

declare const bird: BirdClient;
declare const rawBody: string;
declare const headers: Record<string, string>;

export async function _ex_0() {
const bird = new BirdClient({
  apiKey: process.env.BIRD_API_KEY!,
  region: "eu1", // optional — override the region from the key prefix
  baseUrl: "http://localhost:8080", // optional — overrides region entirely (local/self-hosted)
  timeout: 60_000, // per-attempt timeout in ms (default 60_000)
  maxRetries: 2, // retry budget for transient failures (default 2)
});
}

export async function _ex_1() {
const result = await bird.contacts.batch({
  contacts: [{ email: "jane@acme.com", first_name: "Jane" }],
});
}

export async function _ex_2() {
const contact = await bird.contacts.create({
  email: "jane@acme.com",
  first_name: "Jane",
});
console.log(contact.id); // "con_…"
}

export async function _ex_3() {
await bird.contacts.delete("con_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_4() {
const contact = await bird.contacts.get("con_01krdgeqcxet5s7t44vh8rt9mg");
contact.email;
}

export async function _ex_5() {
for await (const contact of bird.contacts.list({ search: "acme.com" })) {
  console.log(contact.id, contact.email);
}
const page = await bird.contacts.list({ limit: 50 }); // page.data, page.next_cursor
}

export async function _ex_6() {
const contact = await bird.contacts.update("con_01krdgeqcxet5s7t44vh8rt9mg", {
  first_name: "Jane",
});
}

export async function _ex_7() {

try {
  await bird.email.send({
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["delivered@messagebird.dev"],
    subject: "Hello from Bird",
    html: "<p>My first Bird email.</p>",
  });
} catch (err) {
  if (err instanceof BirdRateLimitError) console.log(`rate limited — retry in ${err.retryAfter}s`);
  else if (err instanceof BirdValidationError) console.error(err.details);
  else if (err instanceof BirdAPIError) console.error(err.code, err.requestId);
  else throw err;
}
}

export async function _ex_8() {
const msg = await bird.email.get("em_abc123");
msg.status; // "accepted" | "processed" | "delivered" | "bounced" | …
msg.delivered_count;
msg.bounced_count;
}

export async function _ex_9() {
for await (const message of bird.email.list({ status: "bounced" })) {
  console.log(message.id);
}
}

export async function _ex_10() {
for await (const message of bird.email.list({ status: "bounced" })) {
  console.log(message.id);
}
const page = await bird.email.list({ limit: 50 }); // page.data, page.next_cursor
}

export async function _ex_11() {
const { data, error } = await bird.email
  .send({
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["delivered@messagebird.dev"],
    subject: "Hello from Bird",
    html: "<p>My first Bird email.</p>",
  })
  .safe();
if (error) console.error(error.message);
else console.log(data.id);
}

export async function _ex_12() {
const msg = await bird.email.send({
  from: { email: "onboarding@messagebird.dev", name: "Bird" },
  to: ["delivered@messagebird.dev"],
  subject: "Hello from Bird",
  html: "<p>My first Bird email.</p>",
});
console.log(msg.id, msg.status); // "em_…", "accepted"
}

export async function _ex_13() {
const batch = await bird.email.sendBatch([
  {
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["alice@example.com"],
    subject: "Your receipt",
    html: "<p>Thanks, Alice.</p>",
  },
  {
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["bob@example.com"],
    subject: "Your receipt",
    html: "<p>Thanks, Bob.</p>",
  },
]);
for (const item of batch.data) console.log(item.id, item.status);
}

export async function _ex_14() {
const tpl = await bird.emailTemplates.create({
  name: "welcome-email",
  description: "Welcome",
  category: "transactional",
  source: "handlebars",
  subject: "Welcome, {{ first_name }}!",
  html: "<h1>Hi {{ first_name }}</h1>",
});
console.log(tpl.id, tpl.revision); // "emt_…", 0
}

export async function _ex_15() {
await bird.emailTemplates.delete("emt_abc123");
}

export async function _ex_16() {
const tpl = await bird.emailTemplates.get("emt_abc123");
tpl.subject;
tpl.published_version_id; // null until first publish
}

export async function _ex_17() {
const version = await bird.emailTemplates.getVersion("emt_abc123", "emv_def456");
version.status; // "draft" | "published"
}

export async function _ex_18() {
for await (const tpl of bird.emailTemplates.list({ category: "transactional" })) {
  console.log(tpl.id, tpl.name);
}
const page = await bird.emailTemplates.list({ limit: 50 }); // page.data, page.next_cursor
}

export async function _ex_19() {
const { data } = await bird.emailTemplates.listVersions("emt_abc123");
for (const v of data) console.log(v.version_number, v.status);
}

export async function _ex_20() {
const version = await bird.emailTemplates.publish("emt_abc123");
console.log(version.version_number); // 1, 2, 3…
await bird.email.send({
  from: "hello@acme.com",
  to: ["alice@example.com"],
  template: { id: "emt_abc123", parameters: { first_name: "Alice" } },
});
}

export async function _ex_21() {
const tpl = await bird.emailTemplates.get("emt_abc123");
const updated = await bird.emailTemplates.update("emt_abc123", {
  revision: tpl.revision,
  subject: "Welcome aboard, {{ first_name }}!",
});
}

export async function _ex_22() {
const msg = await bird.sms.get("sms_abc123");
msg.status; // "accepted" | "delivered" | …
}

export async function _ex_23() {
for await (const msg of bird.sms.list({ direction: "outbound" })) {
  console.log(msg.id, msg.status);
}
}

export async function _ex_24() {
const msg = await bird.sms.send({
  to: "+15551234567",
  text: "Your verification code is 123456.",
  category: "authentication",
});
console.log(msg.id, msg.status);
}

export async function _ex_25() {
const result = await bird.sms.sendBatch([
  { to: "+15551111111", text: "Hi Alice!", category: "marketing" },
  { to: "+15552222222", text: "Hi Bob!", category: "marketing" },
]);
}

export async function _ex_26() {
await bird.sms.send({
  to: "+15551234567",
  template: { name: "bird_otp_verification", parameters: { code: "123456" } },
});
}

export async function _ex_27() {
const tpl = await bird.smsTemplates.get("bird_otp_verification");
console.log(tpl.body, tpl.variables);
}

export async function _ex_28() {
const { data } = await bird.smsTemplates.list({ scope: "system" });
for (const tpl of data) console.log(tpl.id, tpl.name);
}

export async function _ex_29() {
// Pass the RAW request body; set the secret via new BirdClient({ webhooks: { secret } }).
const event = bird.webhooks.unwrap(rawBody, headers);
console.log(event.type); // discriminated union — narrow on event.type
}
