// Generated by beak gen:docs-snippets — do not edit. Type-checks every TS
// @example snippet so it cannot drift from the SDK's real types.
import { BirdClient } from "@messagebird/sdk";
import { BirdRateLimitError, BirdValidationError, BirdAPIError } from "@messagebird/sdk";

declare const bird: BirdClient;
declare const rawBody: string;
declare const headers: Record<string, string>;

export async function _ex_0() {
await bird.audiences.addContacts("aud_01krdgeqcxet5s7t44vh8rt9mg", {
  contact_ids: ["con_1", "con_2"],
});
}

export async function _ex_1() {
const audience = await bird.audiences.create({ name: "Newsletter subscribers" });
console.log(audience.id); // "aud_…"
}

export async function _ex_2() {
await bird.audiences.delete("aud_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_3() {
const audience = await bird.audiences.get("aud_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_4() {
for await (const audience of bird.audiences.list()) {
  console.log(audience.id, audience.name);
}
}

export async function _ex_5() {
for await (const member of bird.audiences.listContacts("aud_01krdgeqcxet5s7t44vh8rt9mg")) {
  console.log(member.contact.id, member.joined_at);
}
}

export async function _ex_6() {
await bird.audiences.removeContact("aud_01krdgeqcxet5s7t44vh8rt9mg", "con_1");
}

export async function _ex_7() {
await bird.audiences.removeContacts("aud_01krdgeqcxet5s7t44vh8rt9mg", {
  contact_ids: ["con_1", "con_2"],
});
}

export async function _ex_8() {
await bird.audiences.update("aud_01krdgeqcxet5s7t44vh8rt9mg", { name: "Renamed" });
}

export async function _ex_9() {
const bird = new BirdClient({
  apiKey: process.env.BIRD_API_KEY!,
  region: "eu1", // optional — override the region from the key prefix
  baseUrl: "http://localhost:8080", // optional — overrides region entirely (local/self-hosted)
  timeout: 60_000, // per-attempt timeout in ms (default 60_000)
  maxRetries: 2, // retry budget for transient failures (default 2)
});
}

export async function _ex_10() {
const prop = await bird.contactProperties.archive("cp_01krdgeqcxet5s7t44vh8rt9mg");
console.log(prop.key, prop.archived);
}

export async function _ex_11() {
const prop = await bird.contactProperties.create({ key: "plan", type: "string" });
console.log(prop.id); // "cp_…"
}

export async function _ex_12() {
const prop = await bird.contactProperties.get("cp_01krdgeqcxet5s7t44vh8rt9mg");
console.log(prop.key, prop.type);
}

export async function _ex_13() {
for await (const prop of bird.contactProperties.list()) {
  console.log(prop.key, prop.type);
}
const page = await bird.contactProperties.list({ limit: 50 }); // page.data, page.next_cursor
}

export async function _ex_14() {
await bird.contactProperties.unarchive("cp_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_15() {
await bird.contactProperties.update("cp_01krdgeqcxet5s7t44vh8rt9mg", { fallback_value: "free" });
}

export async function _ex_16() {
const result = await bird.contacts.batch({
  contacts: [{ email: "jane@acme.com", first_name: "Jane" }],
});
}

export async function _ex_17() {
const contact = await bird.contacts.create({
  email: "jane@acme.com",
  first_name: "Jane",
});
console.log(contact.id); // "con_…"
}

export async function _ex_18() {
await bird.contacts.delete("con_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_19() {
const contact = await bird.contacts.get("con_01krdgeqcxet5s7t44vh8rt9mg");
console.log(contact.email, contact.first_name);
}

export async function _ex_20() {
for await (const contact of bird.contacts.list({ q: "acme.com" })) {
  console.log(contact.id, contact.email);
}
const page = await bird.contacts.list({ limit: 50 }); // page.data, page.next_cursor
}

export async function _ex_21() {
const contact = await bird.contacts.update("con_01krdgeqcxet5s7t44vh8rt9mg", {
  first_name: "Jane",
});
}

export async function _ex_22() {
const domain = await bird.domains.create({ domain: "mail.acme.com" });
console.log(domain.id, domain.status); // "dom_…", "pending"
}

export async function _ex_23() {
await bird.domains.delete("dom_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_24() {
const domain = await bird.domains.get("dom_01krdgeqcxet5s7t44vh8rt9mg");
}

export async function _ex_25() {
for await (const domain of bird.domains.list()) {
  console.log(domain.id, domain.status);
}
}

export async function _ex_26() {
await bird.domains.update("dom_01krdgeqcxet5s7t44vh8rt9mg", {
  settings: { click_tracking: true, open_tracking: true },
  tracking: { name: "links" },
});
}

export async function _ex_27() {
const domain = await bird.domains.verify("dom_01krdgeqcxet5s7t44vh8rt9mg");
console.log(domain.status); // "verified" once DNS is in place
}

export async function _ex_28() {
await bird.email.cancel("em_abc123");
}

export async function _ex_29() {

try {
  await bird.email.send({
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["delivered@messagebird.dev"],
    subject: "Hello from Bird",
    html: "<p>My first Bird email.</p>",
  });
} catch (err) {
  if (err instanceof BirdRateLimitError) console.log(`rate limited — retry in ${err.retryAfter}s`);
  else if (err instanceof BirdValidationError) console.error(err.details);
  else if (err instanceof BirdAPIError) console.error(err.code, err.requestId);
  else throw err;
}
}

export async function _ex_30() {
const msg = await bird.email.get("em_abc123");
msg.status; // "accepted" | "processed" | "delivered" | "bounced" | …
msg.delivered_count;
msg.bounced_count;
}

export async function _ex_31() {
for await (const message of bird.email.list({ status: "bounced" })) {
  console.log(message.id);
}
}

export async function _ex_32() {
for await (const message of bird.email.list({ status: "bounced" })) {
  console.log(message.id);
}
const page = await bird.email.list({ limit: 50 }); // page.data, page.next_cursor
}

export async function _ex_33() {
const { data, error } = await bird.email
  .send({
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["delivered@messagebird.dev"],
    subject: "Hello from Bird",
    html: "<p>My first Bird email.</p>",
  })
  .safe();
if (error) console.error(error.message);
else console.log(data.id);
}

export async function _ex_34() {
const msg = await bird.email.send({
  from: { email: "onboarding@messagebird.dev", name: "Bird" },
  to: ["delivered@messagebird.dev"],
  subject: "Hello from Bird",
  html: "<p>My first Bird email.</p>",
});
console.log(msg.id, msg.status); // "em_…", "accepted"
}

export async function _ex_35() {
const batch = await bird.email.sendBatch([
  {
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["alice@example.com"],
    subject: "Your receipt",
    html: "<p>Thanks, Alice.</p>",
  },
  {
    from: { email: "onboarding@messagebird.dev", name: "Bird" },
    to: ["bob@example.com"],
    subject: "Your receipt",
    html: "<p>Thanks, Bob.</p>",
  },
]);
for (const item of batch.data) console.log(item.id, item.status);
}

export async function _ex_36() {
const { data } = await bird.email.stats.byBounceCode({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "bounced",
  limit: 25,
});
for (const row of data) console.log(row.smtp_error_code, row.bounced);
}

export async function _ex_37() {
const { data } = await bird.email.stats.byBroadcast({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "click_rate",
  limit: 25,
});
for (const row of data) console.log(row.broadcast_id, row.engagement.click_rate);
}

export async function _ex_38() {
const { data } = await bird.email.stats.byCategory({ from: "2026-05-01", to: "2026-05-31" });
for (const row of data) console.log(row.category, row.delivery.delivered);
}

export async function _ex_39() {
const { data } = await bird.email.stats.byClient({
  from: "2026-05-01",
  to: "2026-05-31",
  limit: 25,
});
for (const row of data) console.log(row.email_client, row.engagement.unique_opens);
}

export async function _ex_40() {
const { data } = await bird.email.stats.byComplaintType({ from: "2026-05-01", to: "2026-05-31" });
for (const row of data) console.log(row.feedback_type, row.complained);
}

export async function _ex_41() {
const { data } = await bird.email.stats.byLocation({
  from: "2026-05-01",
  to: "2026-05-31",
  limit: 25,
});
for (const row of data) console.log(row.country, row.engagement.unique_opens);
}

export async function _ex_42() {
const { data } = await bird.email.stats.byMailboxProvider({
  from: "2026-05-01",
  to: "2026-05-31",
  limit: 25,
});
for (const row of data) console.log(row.mailbox_provider, row.delivery.delivered);
}

export async function _ex_43() {
const { data } = await bird.email.stats.byMailboxProviderRegion({
  from: "2026-05-01",
  to: "2026-05-31",
  limit: 25,
});
for (const row of data) console.log(row.mailbox_provider, row.mailbox_provider_region, row.delivery.delivered);
}

export async function _ex_44() {
const { data } = await bird.email.stats.byRecipientDomain({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "bounce_rate",
  limit: 25,
});
for (const row of data) console.log(row.recipient_domain, row.delivery.bounce_rate);
}

export async function _ex_45() {
const { data } = await bird.email.stats.bySendingDomain({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "delivery_rate",
  limit: 25,
});
for (const row of data) console.log(row.sending_domain, row.delivery.delivery_rate);
}

export async function _ex_46() {
const { data } = await bird.email.stats.bySendingIp({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "bounces.block",
  limit: 20,
});
for (const row of data) console.log(row.sending_ip, row.delivery.delivered);
}

export async function _ex_47() {
const { data } = await bird.email.stats.byTag({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "delivered",
  limit: 10,
});
for (const row of data) console.log(row.tag, row.delivery.delivered);
}

export async function _ex_48() {
const { data } = await bird.email.stats.byTemplate({
  from: "2026-05-01",
  to: "2026-05-31",
  sort: "open_rate",
  limit: 25,
});
for (const row of data) console.log(row.template_id, row.engagement.open_rate);
}

export async function _ex_49() {
const series = await bird.email.stats.daily({ from: "2026-05-01", to: "2026-05-31" });
for (const row of series.data) console.log(row.bucket, row.delivery.delivered);
}

export async function _ex_50() {
const series = await bird.email.stats.hourly({ from: "2026-05-01", to: "2026-05-02" });
for (const row of series.data) console.log(row.bucket, row.delivery.delivered);
}

export async function _ex_51() {
const s = await bird.email.stats.summary({ from: "2026-05-01", to: "2026-05-31" });
console.log(s.sends_accepted, s.delivery.delivered);
}

export async function _ex_52() {
const msg = await bird.mailbox.compose("mbx_01abc", {
  to: ["customer@example.com"],
  subject: "Hello",
  text: "Hi there!",
});
}

export async function _ex_53() {
const mailbox = await bird.mailbox.create({ display_name: "Support" });
console.log(mailbox.address); // "abc123@inbox.ai"
}

export async function _ex_54() {
await bird.mailbox.delete("mbx_01abc");
}

export async function _ex_55() {
const mailbox = await bird.mailbox.get("mbx_01abc");
console.log(mailbox.state); // "active"
}

export async function _ex_56() {
const labels = await bird.mailbox.labels("mbx_01abc");
console.log(labels.data.map(l => l.name));
}

export async function _ex_57() {
for await (const mailbox of bird.mailbox.list()) {
  console.log(mailbox.address);
}
}

export async function _ex_58() {
const mailbox = await bird.mailbox.restore("mbx_01abc");
}

export async function _ex_59() {
const mailbox = await bird.mailbox.resume("mbx_01abc");
}

export async function _ex_60() {
const stats = await bird.mailbox.stats("mbx_01abc");
console.log(stats.summary?.sends_accepted);
}

export async function _ex_61() {
const mailbox = await bird.mailbox.update("mbx_01abc", { receive_policy: "open" });
}

export async function _ex_62() {
const rule = await bird.mailboxReceiveRule.create("mbx_01abc", {
  action: "block",
  entry: "spam.example.com",
});
}

export async function _ex_63() {
await bird.mailboxReceiveRule.delete("mbx_01abc", "erl_01xyz");
}

export async function _ex_64() {
for await (const rule of bird.mailboxReceiveRule.list("mbx_01abc")) {
  console.log(rule.action, rule.entry);
}
}

export async function _ex_65() {
await bird.mailboxThread.delete("thr_01abc");
}

export async function _ex_66() {
const thread = await bird.mailboxThread.get("thr_01abc");
console.log(thread.message_count);
}

export async function _ex_67() {
for await (const thread of bird.mailboxThread.list()) {
  console.log(thread.id, thread.message_count);
}
}

export async function _ex_68() {
const thread = await bird.mailboxThread.update("thr_01abc", {
  labels: { add: ["archive"] },
});
}

export async function _ex_69() {
const atts = await bird.mailboxThreadMessage.attachments("thr_01abc", "rem_01xyz");
console.log(atts.data.map(a => a.filename));
}

export async function _ex_70() {
const body = await bird.mailboxThreadMessage.body("thr_01abc", "rem_01xyz");
console.log(body.text);
}

export async function _ex_71() {
const msg = await bird.mailboxThreadMessage.get("thr_01abc", "rem_01xyz");
console.log(msg.direction); // "inbound"
}

export async function _ex_72() {
for await (const msg of bird.mailboxThreadMessage.list("thr_01abc")) {
  console.log(msg.id, msg.direction);
}
}

export async function _ex_73() {
const reply = await bird.mailboxThreadMessage.reply("thr_01abc", "rem_01xyz", {
  text: "Thanks for reaching out!",
});
}

export async function _ex_74() {
const msg = await bird.sms.get("sms_abc123");
msg.status; // "accepted" | "delivered" | …
}

export async function _ex_75() {
for await (const msg of bird.sms.list({ direction: "outbound" })) {
  console.log(msg.id, msg.status);
}
}

export async function _ex_76() {
const msg = await bird.sms.send({
  from: "MyBrand",
  to: "+14155550100",
  text: "Your verification code is 123456.",
  category: "authentication",
});
console.log(msg.id, msg.status);
}

export async function _ex_77() {
const result = await bird.sms.sendBatch([
  { to: "+15551111111", text: "Hi Alice!", category: "marketing" },
  { to: "+15552222222", text: "Hi Bob!", category: "marketing" },
]);
}

export async function _ex_78() {
await bird.sms.send({
  to: "+14155550100",
  template: { name: "bird_otp_verification", parameters: { code: "123456" } },
});
}

export async function _ex_79() {
const tpl = await bird.smsTemplates.get("bird_otp_verification");
console.log(tpl.body, tpl.variables);
}

export async function _ex_80() {
const { data } = await bird.smsTemplates.list({ scope: "system" });
for (const tpl of data) console.log(tpl.id, tpl.name);
}

export async function _ex_81() {
const result = await bird.verify.verifications.check({
  to: { phone_number: "+15551234567" },
  code: "123456",
});
console.log(result.success);
}

export async function _ex_82() {
const verification = await bird.verify.verifications.create({
  to: { phone_number: "+15551234567" },
});
console.log(verification.id, verification.status);
}

export async function _ex_83() {
// Pass the RAW request body; set the secret via new BirdClient({ webhooks: { secret } }).
const event = bird.webhooks.unwrap(rawBody, headers);
console.log(event.type); // discriminated union: narrow on event.type
}

export async function _ex_84() {
const msg = await bird.whatsapp.get("wa_abc123");
msg.status; // "accepted" | "delivered" | …
}

export async function _ex_85() {
for await (const msg of bird.whatsapp.list({ status: ["delivered"] })) {
  console.log(msg.id, msg.status);
}
}

export async function _ex_86() {
const { data } = await bird.whatsapp.listEvents("wa_abc123");
for (const event of data) console.log(event.type, event.occurred_at);
}

export async function _ex_87() {
const msg = await bird.whatsapp.send({
  to: "+15551234567",
  template: {
    name: "bird_otp",
    components: [
      { type: "body", parameters: [{ type: "text", text: "123456" }] },
    ],
  },
});
console.log(msg.id, msg.status);
}

export async function _ex_88() {
const { data } = await bird.whatsappTemplates.list();
for (const tpl of data) console.log(tpl.name, tpl.status);
}
