// Code generated by openapi/scripts/eventconst-gen.go. DO NOT EDIT.

/**
 * Webhook event types known at this SDK version. The wire value is an open
 * string: a value added by a newer server is returned by `unwrap` unchanged,
 * so switch on these with a `default` branch.
 */
export const WebhookEventType = {
  DomainFailed: "domain.failed",
  DomainVerified: "domain.verified",
  EmailAccepted: "email.accepted",
  EmailBounced: "email.bounced",
  EmailClicked: "email.clicked",
  EmailComplained: "email.complained",
  EmailDeferred: "email.deferred",
  EmailDelivered: "email.delivered",
  EmailListUnsubscribed: "email.list_unsubscribed",
  EmailOpened: "email.opened",
  EmailOutOfBandBounce: "email.out_of_band_bounce",
  EmailProcessed: "email.processed",
  EmailReceived: "email.received",
  EmailRejected: "email.rejected",
  EmailSuppressionCreated: "email_suppression.created",
  EmailUnsubscribed: "email.unsubscribed",
  SmsAccepted: "sms.accepted",
  SmsDelivered: "sms.delivered",
  SmsExpired: "sms.expired",
  SmsFailed: "sms.failed",
  SmsRejected: "sms.rejected",
  SmsSent: "sms.sent",
  SmsUndelivered: "sms.undelivered",
} as const;

/** A known webhook event type value. */
export type WebhookEventTypeValue =
  (typeof WebhookEventType)[keyof typeof WebhookEventType];
