// Code generated by surface-gen; DO NOT EDIT.
// Every catalogued sdk method must exist on the client; a missing or renamed
// method makes a Pick reference a non-existent key and fails `tsc --noEmit`.
// Generated from backend/openapi/surfaces.ir.json.
import type { BirdClient } from "./client.js";

export type _Email = Pick<BirdClient["email"], "send" | "sendBatch" | "get" | "list">;
export type _Webhooks = Pick<BirdClient["webhooks"], "unwrap">;
