// Code generated by surface-gen; DO NOT EDIT.
// Every catalogued sdk method must exist on the client; a missing or renamed
// method makes a Pick reference a non-existent key and fails `tsc --noEmit`.
// Generated from backend/openapi/surfaces.ir.json.
import type { BirdClient } from "./client.js";

export type _Email = Pick<BirdClient["email"], "send" | "sendBatch" | "get" | "list" | "cancel">;
export type _Sms = Pick<BirdClient["sms"], "send" | "sendBatch" | "get" | "list">;
export type _SmsTemplates = Pick<BirdClient["smsTemplates"], "list" | "get">;
export type _Webhooks = Pick<BirdClient["webhooks"], "unwrap">;
export type _Contacts = Pick<BirdClient["contacts"], "list" | "get" | "create" | "update" | "delete" | "batch">;
export type _ContactProperties = Pick<BirdClient["contactProperties"], "list" | "get" | "create" | "update" | "archive" | "unarchive">;
export type _Audiences = Pick<BirdClient["audiences"], "list" | "get" | "create" | "update" | "delete" | "listContacts" | "addContacts" | "removeContacts" | "removeContact">;
